update_target: payment
order:
  id: 2025-02-10-293522
  fulfillments:
    - id: c_e1ef592c-5ccf-476b-97c8-85f276f07b53_1
      type: Cancel
  payment:
    '@ondc/org/settlement_details':
      - settlement_counterparty: buyer
        settlement_phase: refund
        settlement_type: netbanking
        settlement_amount: '500'
        settlement_timestamp: '2025-02-10T07:32:18.275Z'
