order:
  id: O1
  state: Created
  billing:
    address:
      building: my building name or house
      city: Bengaluru
      state: Karnataka
      country: IND
      area_code: "560027"
      locality: my street name
      name: my house or door or floor
    phone: "9898989898"
    name: ONDC buyer
    email: nobody@nomail.com
    created_at: "2024-08-14T09:10:34.369Z"
    updated_at: "2024-08-14T09:10:34.369Z"
  items:
    - id: I1
      quantity:
        count: 1
      fulfillment_id: F1
  provider:
    id: P1
    locations:
      - id: L1
    creds:
    - id: gi-12345678
      descriptor:
        code: Social Sector
        short_desc: GI
  fulfillments:
    - "@ondc/org/TAT": P3D
      id: F1
      tracking: true
      end:
        contact:
          email: nobody@nomail.com
          phone: "9898989898"
        person:
          name: ONDC Buyer
        location:
          gps: 12.966545,77.592074
          address:
            building: my building name or house
            city: Bengaluru
            state: Karnataka
            country: IND
            area_code: "560027"
            locality: my street name
            name: my house or door or floor
      type: Delivery
  payment:
    params:
      amount: "2756.75"
      currency: INR
      transaction_id: order_PjggJp7MccQmAa
    status: PAID
    type: ON-ORDER
    collected_by: BAP
    uri: "https://razorpay.com/"
    "tl_method": "http/get"
    "@ondc/org/buyer_app_finder_fee_type": percent
    "@ondc/org/buyer_app_finder_fee_amount": "3.0"
    "@ondc/org/settlement_details":
      - settlement_counterparty: seller-app
        settlement_phase: sale-amount
        settlement_type: neft
        beneficiary_name: xxxx
        settlement_bank_account_no: XXXX
        settlement_ifsc_code: XXXX
        bank_name: XXXX
        branch_name: XXXX
  quote:
    price:
      currency: INR
      value: "2756.75"
    breakup:
      - "@ondc/org/item_id": I1
        "@ondc/org/item_quantity":
          count: 1
        title: Butterfly Beutiful 13 Gold Necklace
        "@ondc/org/title_type": item
        price:
          currency: INR
          value: "2260.00"
        item:
          price:
            currency: INR
            value: "2260.00"
      - "@ondc/org/item_id": F1
        title: Delivery charges
        "@ondc/org/title_type": delivery
        price:
          currency: INR
          value: "493.75"
      - "@ondc/org/item_id": F1
        title: Convenience Fee
        "@ondc/org/title_type": misc
        price:
          currency: INR
          value: "3.00"
    ttl: P1D
  tags:
    - code: bpp_terms
      list:
        - code: np_type
          value: MSN
        - code: tax_number
          value: 37ABACA6712B1Z6
        - code: provider_tax_number
          value: USYDS6482D
    - code: bap_terms
      list:
        - code: tax_number
          value: 37BABCA6712B1Z6
  created_at: "2024-08-14T09:11:00.810Z"
  updated_at: "2024-08-14T09:11:00.810Z"
