message:
  order:
    provider:
      id: 98ec8346-b8eb-42c2-9ecd-615c944ea91a
      locations:
        - id: 672b37d163f0cee7ee2bc4c7
    fulfillments:
      - id: 4c2e2ce2-2e04-4bf9-b500-85faf0366a61
        type: Delivery
        '@ondc/org/provider_name': Epic Store
        tracking: false
        '@ondc/org/category': Standard Delivery
        '@ondc/org/TAT': P3D
        state:
          descriptor:
            code: Serviceable
    quote:
      price:
        value: '81658.96'
        currency: INR
      breakup:
        - '@ondc/org/item_id': cc7e2f62-efbe-4665-ad1d-9388781abade
          '@ondc/org/item_quantity':
            count: 2
          title: Golden Ring by saad
          '@ondc/org/title_type': item
          price:
            currency: INR
            value: '81658.96'
          item:
            quantity:
              available:
                count: '99'
              maximum:
                count: '10'
            price:
              currency: INR
              value: '40829.48'
        - '@ondc/org/item_id': 4c2e2ce2-2e04-4bf9-b500-85faf0366a61
          title: Delivery charges
          '@ondc/org/title_type': delivery
          price:
            currency: INR
            value: '0.00'
      ttl: P1D
    items:
      - id: cc7e2f62-efbe-4665-ad1d-9388781abade
        fulfillment_id: 4c2e2ce2-2e04-4bf9-b500-85faf0366a61
