order:
  provider:
    id: oc_22
    locations:
      - id: location_15
  items:
    - fulfillment_id: 05fddb5e0d6bfe1251975d039599c525
      id: oc_72
  quote:
    price:
      currency: INR
      value: '2500.00'
    breakup:
      - '@ondc/org/item_id': oc_72
        '@ondc/org/item_quantity':
          count: 5
        title: Pavizham Rice 10KG
        '@ondc/org/title_type': item
        price:
          currency: INR
          value: '2500.00'
        item:
          quantity:
            available:
              count: '99'
            maximum:
              count: '10'
          price:
            currency: INR
            value: '500.00'
      - '@ondc/org/item_id': 05fddb5e0d6bfe1251975d039599c525
        title: Delivery Charges
        '@ondc/org/title_type': delivery
        price:
          currency: INR
          value: '0.00'
    ttl: P1D
  fulfillments:
    - id: 05fddb5e0d6bfe1251975d039599c525
      type: Delivery
      '@ondc/org/provider_name': Opencart Vendor1
      tracking: false
      '@ondc/org/category': Immediate Delivery
      '@ondc/org/TAT': PT2H
      state:
        descriptor:
          code: Serviceable
