order:
  provider:
    id: P1
    locations:
      - id: L1
  fulfillments:
    - id: F1
      type: Delivery
      "@ondc/org/provider_name": LSP or Provider Name
      tracking: true
      "@ondc/org/category": Standard Delivery
      "@ondc/org/TAT": P3D
      state:
        descriptor:
          code: Serviceable
  quote:
    price:
      value: "0"
      currency: INR
    breakup:
      - "@ondc/org/item_id": I3
        "@ondc/org/item_quantity":
          count: 0
        title: Butterfly Beautiful 13 Gold Necklace
        "@ondc/org/title_type": item
        price:
          currency: INR
          value: "0"
        item:
          quantity:
            available:
              count: "0"
            maximum:
              count: "0"
          price:
            currency: INR
            value: "0.00"
      - "@ondc/org/item_id": F1
        title: Delivery charges
        "@ondc/org/title_type": delivery
        price:
          currency: INR
          value: "0"
      - "@ondc/org/item_id": F1
        title: Convenience Fee
        "@ondc/org/title_type": misc
        price:
          currency: INR
          value: "0"
    ttl: P1D
  items:
    - id: I3
      fulfillment_id: F1
  error:
    type: DOMAIN-ERROR
    code: "40002"
    message: "[{\"item_id\":\"I3\",\"error\":\"40002\"}]"