catalog:
  bpp/fulfillments:
    - id: F1
      type: Delivery
  bpp/descriptor:
    name: Mock Seller NP
    symbol: https://sellerNP.com/images/np.png
    short_desc: Seller Marketplace
    long_desc: Seller Marketplace
    images:
      - https://sellerNP.com/images/np.png
    tags:
      - code: bpp_terms
        list:
          - code: np_type
            value: MSN
  bpp/providers:
    - id: P1
      time:
        label: enable
        timestamp: "2024-08-13T06:46:19.736Z"
      ttl: PT24H
      locations:
        - id: L1
          gps: 12.925810,77.583624
          address:
            city: Bengaluru
            state: Karnataka
            area_code: "560011"
            street: Jayanagar
            locality: Jayanagar
          time:
            label: enable
            timestamp: "2024-08-13T06:46:19.736Z"
            days: 1,2,3,4,5
            schedule:
              holidays: []
            range:
              start: "0000"
              end: "2359"
          circle:
            gps: 12.925810,77.583624
            radius:
              unit: km
              value: "5"
      descriptor:
        name: Store 1
        symbol: https://sellerNP.com/images/store1.png
        short_desc: Store 1
        long_desc: Store 1
        images:
          - https://sellerNP.com/images/store1.png
      categories:
        - id: V1
          descriptor:
            name: Variant Group 1
          tags:
            - code: type
              list:
                - code: type
                  value: variant_group
            - code: attr
              list:
                - code: name
                  value: item.tags.attribute.colour
                - code: seq
                  value: "1"
      items:
        - id: I1
          time:
            label: enable
            timestamp: "2024-08-12T05:30:48.998Z"
          parent_item_id: ""
          descriptor:
            name: Power Bank
            symbol: https://sellerNP.com/images/i1.png
            short_desc: A Power Bank is a portable charger designed to recharge your electronic devices when you're on the move. Ranging in size from slim, pocket-sized devices up to larger, higher-capacity Power Banks – they can be used to charge smartphones, tablets, earphones, smartwatches and other mobile devices.
            long_desc: A Power Bank is a portable charger designed to recharge your electronic devices when you're on the move. Ranging in size from slim, pocket-sized devices up to larger, higher-capacity Power Banks
            images:
              - https://sellerNP.com/images/i1.png
            code: 5:ESS45300
          quantity:
            unitized:
              measure:
                unit: unit
                value: "1"
            available:
              count: "99"
            maximum:
              count: "8"
          price:
            currency: INR
            value: "2260"
            maximum_value: "2260"
          category_id: Power Bank
          location_id: L1
          fulfillment_id: F1
          "@ondc/org/returnable": true
          "@ondc/org/cancellable": true
          "@ondc/org/available_on_cod": false
          "@ondc/org/time_to_ship": P2D
          "@ondc/org/seller_pickup_return": true
          "@ondc/org/return_window": P7D
          "@ondc/org/contact_details_consumer_care": Seller Business,test@gmail.com,9876543210
          "@ondc/org/statutory_reqs_packaged_commodities":
            manufacturer_or_packer_name: Seller Business
            manufacturer_or_packer_address: Seller Building Address, Jayanagar, Bengaluru, Karnataka, India - 560011
            common_or_generic_name_of_commodity: Power Bank
            month_year_of_manufacture_packing_import: NA
          tags:
            - code: origin
              list:
                - code: country
                  value: IND
            - code: attribute
              list:
                - code: brand
                  value: Shiv Electricals
                - code: weight
                  value: "103"
                - code: model
                  value: "2012"
                - code: breadth
                  value: "12.3"
                - code: length
                  value: "10.2"
                - code: height
                  value: "15.5"
        
        - id: I2
          time:
            label: enable
            timestamp: "2024-08-12T10:27:48.913Z"
          parent_item_id: ""
          descriptor:
            name: Adaptor  25W C  type
            symbol: https://sellerNP.com/images/i1.png
            short_desc: An adapter or adaptor is a device that converts attributes of one electrical device or system to those of an otherwise incompatible device or system. Some modify power or signal attributes, while others merely adapt the physical form of one connector to another.
            long_desc: An adapter or adaptor is a device that converts attributes of one electrical device or system to those of an otherwise incompatible device or system. Some modify power or signal attributes, while others merely adapt the physical form of one connector to another.
            images:
              - https://sellerNP.com/images/i1.png
            code: 5:ESS45391
          quantity:
            unitized:
              measure:
                unit: unit
                value: "1"
            available:
              count: "99"
            maximum:
              count: "10"
          price:
            currency: INR
            value: "2460"
            maximum_value: "2460"
          category_id: Adapter
          location_id: L1
          fulfillment_id: F1
          "@ondc/org/returnable": true
          "@ondc/org/cancellable": true
          "@ondc/org/available_on_cod": false
          "@ondc/org/time_to_ship": P2D
          "@ondc/org/seller_pickup_return": true
          "@ondc/org/return_window": P7D
          "@ondc/org/contact_details_consumer_care": Seller Business,test@gmail.com,9876543210
          "@ondc/org/statutory_reqs_packaged_commodities":
            manufacturer_or_packer_name: Seller Business
            manufacturer_or_packer_address: Seller Building Address, Jayanagar, Bengaluru, Karnataka, India - 560011
            common_or_generic_name_of_commodity: Adaptor  25W C  type
            month_year_of_manufacture_packing_import: NA
          tags:
            - code: origin
              list:
                - code: country
                  value: IND
            - code: attribute
              list:
                - code: colour
                  value: "#FF69B4"
                - code: brand
                  value: Shiv Electricals
        - id: I3
          descriptor:
            name: Charger 360plus 4500mah
            code: 5:ESS45399
            symbol: https://sellerNP.com/images/i1.png
            short_desc: Bring home this compact charger from boAt and keep your phone charged at all times. The Auto-detect charging feature keeps your devices charged by adapting to your device’s charging requirements. The Quick Charge 3.0 technology provides lightning-fast speeds of charging. Moreover, your charger is also protected from short circuits, overheating and overcurrent, thanks to the inbuilt Smart IC Protection feature.
            long_desc: Bring home this compact charger from boAt and keep your phone charged at all times. The Auto-detect charging feature keeps your devices charged by adapting to your device’s charging requirements. The Quick Charge 3.0 technology provides lightning-fast speeds of charging. Moreover, your charger is also protected from short circuits, overheating and overcurrent
            images:
              - https://sellerNP.com/images/i1.png
          price:
            currency: INR
            value: "499.00"
            maximum_value: "1199.00"
          parent_item_id: V1
          category_id: Charger
          fulfillment_id: F1
          location_id: L1
          time:
            label: enable
            timestamp: "2024-08-12T10:27:48.913Z"
          related: true
          recommended: true
          quantity:
            available:
              count: "99"
            maximum:
              count: "99"
            unitized:
              measure:
                value: "1"
                unit: unit
          "@ondc/org/returnable": true
          "@ondc/org/seller_pickup_return": false
          "@ondc/org/return_window": P3D
          "@ondc/org/cancellable": true
          "@ondc/org/time_to_ship": P1D
          "@ondc/org/available_on_cod": false
          "@ondc/org/contact_details_consumer_care": Dailywear Fashion,support@gmail.com,2343453434
          "@ondc/org/statutory_reqs_packaged_commodities":
            manufacturer_or_packer_name: Seller Business
            manufacturer_or_packer_address: Seller Building Address, Jayanagar, Bengaluru, Karnataka, India - 560011
            common_or_generic_name_of_commodity: Adaptor  25W C  type
            month_year_of_manufacture_packing_import: NA
          tags:
            - code: origin
              list:
                - code: country
                  value: IND
            - code: attribute
              list:
                - code: colour
                  value: "#0B0B3B"
                - code: brand
                  value: Shiv Electricals
        - id: I4
          descriptor:
            name: Charger 360plus 4500mah
            code: 5:ESS45450
            symbol: https://sellerNP.com/images/i1.png
            short_desc: Bring home this compact charger from boAt and keep your phone charged at all times. The Auto-detect charging feature keeps your devices charged by adapting to your device’s charging requirements. The Quick Charge 3.0 technology provides lightning-fast speeds of charging. Moreover, your charger is also protected from short circuits, overheating and overcurrent, thanks to the inbuilt Smart IC Protection feature.
            long_desc: Bring home this compact charger from boAt and keep your phone charged at all times. The Auto-detect charging feature keeps your devices charged by adapting to your device’s charging requirements. The Quick Charge 3.0 technology provides lightning-fast speeds of charging. Moreover, your charger is also protected from short circuits, overheating and overcurrent
            images:
              - https://sellerNP.com/images/i1.png
          price:
            currency: INR
            value: "599.00"
            maximum_value: "1199.00"
          parent_item_id: V1
          category_id: Charger
          fulfillment_id: F1
          location_id: L1
          time:
            label: enable
            timestamp: "2024-08-12T10:27:48.913Z"
          related: true
          recommended: true
          quantity:
            available:
              count: "99"
            maximum:
              count: "99"
            unitized:
              measure:
                value: "1"
                unit: unit
          "@ondc/org/returnable": true
          "@ondc/org/seller_pickup_return": false
          "@ondc/org/return_window": P3D
          "@ondc/org/cancellable": true
          "@ondc/org/time_to_ship": P1D
          "@ondc/org/available_on_cod": false
          "@ondc/org/contact_details_consumer_care": Dailywear Fashion,support@gmail.com,2343453434
          "@ondc/org/statutory_reqs_packaged_commodities":
            manufacturer_or_packer_name: Seller Business
            manufacturer_or_packer_address: Seller Building Address, Jayanagar, Bengaluru, Karnataka, India - 560011
            common_or_generic_name_of_commodity: Adaptor  25W C  type
            month_year_of_manufacture_packing_import: NA
          tags:
            - code: origin
              list:
                - code: country
                  value: IND
            - code: attribute
              list:
                - code: colour
                  value: "#FF69B4"
                - code: brand
                  value: Shiv Electricals
      fulfillments:
        - id: F1
          type: Delivery
          contact:
            phone: "9876543210"
            email: test@gmail.com
      creds:
        - id: gi-12345678
          descriptor:
            code: Social Sector
            short_desc: GI
          url: https://abcd.cdn.com/images/badge-img
          tags:
            - code: verification
              list:
                - code: verify_url
                  value: https://abcd.gi.com/verify?id=gi-12345678'
                - code: verifier
                  value: CSP-ABC
                - code: issuer
                  value: Example Authority
                - code: valid_from
                  value: 2023-06-03T00:00:00:000Z
                - code: valid_to
                  value: 2024-06-03T23:59:59:999Z
      tags:
        - code: serviceability
          list:
            - code: location
              value: L1
            - code: category
              value: Power Bank
            - code: type
              value: "12"
            - code: unit
              value: country
            - code: val
              value: IND
        - code: serviceability
          list:
            - code: location
              value: L1
            - code: category
              value: Adapter
            - code: type
              value: "12"
            - code: unit
              value: country
            - code: val
              value: IND
        - code: serviceability
          list:
            - code: location
              value: L1
            - code: category
              value: Charger
            - code: type
              value: "12"
            - code: unit
              value: country
            - code: val
              value: IND
        - code: timing
          list:
            - code: type
              value: All
            - code: location
              value: L1
            - code: day_from
              value: "1"
            - code: day_to
              value: "5"
            - code: time_from
              value: "0000"
            - code: time_to
              value: "2359"
