update_target: item
order:
  id: O1
  fulfillments:
    - type: Return
      tags:
        - code: return_request
          list:
            - code: id
              value: R1
            - code: item_id
              value: I1
            - code: parent_item_id
              value: ""
            - code: item_quantity
              value: "1"
            - code: reason_id
              value: "001"
            - code: reason_desc
              value: detailed description for return
            - code: images
              value: https://sellerNP.com/images/store1.png
            - code: ttl_approval
              value: PT24H
            - code: ttl_reverseqc
              value: P3D
            - code: replace
              value: "yes"
