order:
  provider:
    id: 5b3981a7-512d-4ac4-bd75-ea48eff89a53
    locations:
      - id: 668e238e1b106d310473ddb0
  items:
    - id: 839cb128-34bd-444d-9ffc-05903e62b35a
      quantity:
        count: 1
      location_id: 668e238e1b106d310473ddb0
      fulfillment_id: 3ac6a056-ceba-4c14-8e5d-ab5dd72d5239
  billing:
    address:
      building: New_Building
      city: Bengaluru
      state: Karnataka
      country: IND
      area_code: '560027'
      locality: 6th Cross Road
      name: Tanishq Mishra
    phone: '9399788618'
    name: Tanishq Mishra
    email: mishratanishq619@gmail.com
    created_at: '2024-08-08T10:01:24.650Z'
    updated_at: '2024-08-08T10:01:24.650Z'
  fulfillments:
    - id: 3ac6a056-ceba-4c14-8e5d-ab5dd72d5239
      type: Delivery
      end:
        contact:
          email: mishratanishq619@gmail.com
          phone: '9399788618'
        location:
          gps: 12.966545,77.592074
          address:
            building: New_Building
            city: Bengaluru
            state: Karnataka
            country: IND
            area_code: '560027'
            locality: 6th Cross Road
            name: Tanishq Mishra
