message:
  intent:
    payment:
      "@ondc/org/buyer_app_finder_fee_type": percent
      "@ondc/org/buyer_app_finder_fee_amount": "3"
    tags:
      - code: catalog_inc
        list:
          - code: mode
            value: start
