message:
  catalog:
    bpp/providers:
      - id: 98ec8346-b8eb-42c2-9ecd-615c944ea91a
        locations:
          - id: 672b37d163f0cee7ee2bc4c7
            time:
              label: close
              timestamp: "2025-01-08T10:20:00.000Z"
              range:
                start: "2025-01-08T16:00:00.000Z"
                end: "2025-01-08T23:59:00.000Z"
