message:
  order:
    id: O1
    state: Created
    provider:
      id: P1
      locations:
        - id: L1
    items:
      - id: I1
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI1
        tags:
          - code: type
            list:
              - code: type
                value: item
      - id: C1
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI1
        tags:
          - code: type
            list:
              - code: type
                value: customization
          - code: parent
            list:
              - code: id
                value: CG1
      - id: C7
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI1
        tags:
          - code: type
            list:
              - code: type
                value: customization
          - code: parent
            list:
              - code: id
                value: CG2
      - id: C14
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI1
        tags:
          - code: type
            list:
              - code: type
                value: customization
          - code: parent
            list:
              - code: id
                value: CG3
      - id: C16
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI1
        tags:
          - code: type
            list:
              - code: type
                value: customization
          - code: parent
            list:
              - code: id
                value: CG3
      - id: I1
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI2
        tags:
          - code: type
            list:
              - code: type
                value: item
      - id: C2
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI2
        tags:
          - code: type
            list:
              - code: type
                value: customization
          - code: parent
            list:
              - code: id
                value: CG1
      - id: C7
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI2
        tags:
          - code: type
            list:
              - code: type
                value: customization
          - code: parent
            list:
              - code: id
                value: CG2
    billing:
      name: ONDC buyer
      address:
        name: my house or door or floor #
        building: my building name or house #
        locality: my street name
        city: Bengaluru
        state: Karnataka
        country: IND
        area_code: "560037"
      phone: "9886098860"
      email: nobody@nomail.com
      created_at: "2025-01-08T09:00:00.000Z"
      updated_at: "2025-01-08T09:00:00.000Z"
    fulfillments:
      - id: F1
        type: Delivery
        "@ondc/org/TAT": PT60M
        tracking: false
        end:
          person:
            name: name_of_person
          contact:
            email: nobody@nomail.com
            phone: "9886098860"
          location:
            gps: 12.4535,77.9283
            address:
              name: my house or door or floor #
              building: my building name or house #
              locality: my street name
              city: Bengaluru
              state: Karnataka
              country: IND
              area_code: "560037"
    quote:
      price:
        currency: INR
        value: "1955.65"
      breakup:
        - "@ondc/org/item_id": I1
          "@ondc/org/item_quantity":
            count: 1
          title: Farm House Pizza
          "@ondc/org/title_type": item
          price:
            currency: INR
            value: "269.00"
          item:
            parent_item_id: DI1
            price:
              currency: INR
              value: "269.00"
            tags:
              - code: type
                list:
                  - code: type
                    value: item
        - "@ondc/org/item_id": C1
          "@ondc/org/item_quantity":
            count: 1
          title: New Hand Tossed
          "@ondc/org/title_type": item
          price:
            currency: INR
            value: "0.00"
          item:
            parent_item_id: DI1
            price:
              currency: INR
              value: "0.00"
            tags:
              - code: type
                list:
                  - code: type
                    value: customization
              - code: parent
                list:
                  - code: id
                    value: CG1
        - "@ondc/org/item_id": C7
          "@ondc/org/item_quantity":
            count: 1
          title: Large
          "@ondc/org/title_type": item
          price:
            currency: INR
            value: "450.00"
          item:
            parent_item_id: DI1
            price:
              currency: INR
              value: "450.00"
            tags:
              - code: type
                list:
                  - code: type
                    value: customization
              - code: parent
                list:
                  - code: id
                    value: CG2
      ttl: PT1H
    payment:
      params:
        currency: INR
        transaction_id: "3937"
        amount: "1955.65"
      status: PAID
      type: ON-ORDER
      collected_by: BAP
      "@ondc/org/buyer_app_finder_fee_type": percent
      "@ondc/org/buyer_app_finder_fee_amount": "3"
      "@ondc/org/settlement_basis": delivery
      "@ondc/org/settlement_window": P1D
      "@ondc/org/withholding_amount": "10.00"
      "@ondc/org/settlement_details":
        - settlement_counterparty: seller-app
          settlement_phase: sale-amount
          settlement_type: upi
          upi_address: gft@oksbi
          settlement_bank_account_no: XXXXXXXXXX
          settlement_ifsc_code: XXXXXXXXX
          beneficiary_name: xxxxx
          bank_name: xxxx
          branch_name: xxxx
    tags:
      - code: bpp_terms
        list:
          - code: tax_number
            value: 12ABCDE3456FGZH
          - code: np_type
            value: BAP
      - code: bap_terms
        list:
          - code: accept_bpp_terms
            value: Y
          - code: static_terms
            value: https://github.com/ONDC-Official/NP-Static-Terms/buyerNP_BNP/1.0/tc.pdf
          - code: tax_number
            value: 12ABCDE3456FGZJ
    created_at: "2025-01-08T09:30:00.000Z"
    updated_at: "2025-01-08T09:30:00.000Z"
