order:
  provider:
    id: P1
    locations:
      - id: L1
  state: Completed
  items:
    - id: I1
      quantity:
        count: 3
      fulfillment_id: F1
    - id: I1
      fulfillment_id: C1
      quantity:
        count: 4
  billing:
    address:
      name: my house or door or floor
      building: my building name or house
      locality: my street name
      city: Bengaluru
      state: Karnataka
      country: IND
      area_code: "560027"
    phone: "9898989898"
    name: ONDC Buyer
    email: nobody@nomail.com
    created_at: "2024-08-14T09:10:34.369Z"
    updated_at: "2024-08-14T09:10:34.369Z"
  fulfillments:
    - id: F1
      "@ondc/org/provider_name": Seller Business
      "@ondc/org/TAT": PT72H
      state:
        descriptor:
          code: Order-delivered
      type: Delivery
      tracking: false
      start:
        location:
          id: L1
          descriptor:
            name: Seller Business
          gps: 12.92580970146639,77.58362409712942
          address:
            locality: Jayanagar
            city: Bengaluru
            area_code: "560011"
            state: Karnataka
        contact:
          email: test@gmail.com
          phone: "9876543210"
        time:
          range:
            start: "2024-08-08T12:39:03.396Z"
            end: "2024-08-10T12:39:03.396Z"
          timestamp: "2024-08-08T12:40:22.763Z"
      end:
        person:
          name: ONDC Buyer
        contact:
          email: nobody@nomail.com
          phone: "9898989898"
        location:
          gps: 12.966545,77.592074
          address:
            name: my house or door or floor
            building: my building name or house
            locality: my street name
            city: Bengaluru
            state: Karnataka
            country: IND
            area_code: "560027"
        time:
          range:
            start: "2024-08-11T12:39:03.396Z"
            end: "2024-08-13T12:39:03.396Z"
          timestamp: "2024-08-08T12:41:02.913Z"
    - state:
        descriptor:
          code: Cancelled
      type: Cancel
      id: C1
      tags:
        - code: cancel_request
          list:
            - code: reason_id
              value: "002"
            - code: initiated_by
              value: your id
        - code: quote_trail
          list:
            - code: type
              value: item
            - code: id
              value: I1
            - code: currency
              value: INR
            - code: value
              value: "-9040.00"
    - id: R1
      type: Return
      state:
        descriptor:
          code: Return_Initiated
      tags:
        - code: return_request
          list:
            - code: id
              value: R1
            - code: item_id
              value: I1
            - code: parent_item_id
              value: ""
            - code: item_quantity
              value: "1"
            - code: reason_id
              value: "001"
            - code: reason_desc
              value: detailed description for return
            - code: images
              value: https://sellerNP.com/images/store1.png
            - code: ttl_approval
              value: PT24H
            - code: ttl_reverseqc
              value: P3D
            - code: initiated_by
              value: your id
  quote:
    price:
      currency: INR
      value: "7373.75"
    breakup:
      - "@ondc/org/item_id": I1
        "@ondc/org/item_quantity":
          count: 3
        title: Butterfly Beutiful 12 Gold Necklace
        "@ondc/org/title_type": item
        price:
          currency: INR
          value: "6780"
        item:
          price:
            currency: INR
            value: "2260.00"
      - "@ondc/org/item_id": F1
        title: Delivery charges
        "@ondc/org/title_type": delivery
        price:
          currency: INR
          value: "493.75"
      - "@ondc/org/item_id": F1
        title: Convenience Fee
        "@ondc/org/title_type": misc
        price:
          currency: INR
          value: "100.00"
    ttl: P1D
  payment:
    uri: your payment uri
    tl_method: http/get
    params:
      amount: "16413.75"
      currency: INR
      transaction_id: order_Okj0iihMKJod0V
    status: PAID
    type: ON-ORDER
    collected_by: BAP
    "@ondc/org/buyer_app_finder_fee_type": percent
    "@ondc/org/buyer_app_finder_fee_amount": "3.0"
    "@ondc/org/settlement_details":
      - settlement_counterparty: seller-app
        settlement_phase: sale-amount
        settlement_type: neft
        upi_address: xxxx
        settlement_bank_account_no: xxxx
        settlement_ifsc_code: xxxx
        beneficiary_name: xxxx
        bank_name: xxxx
        branch_name: xxxx
      - settlement_counterparty: buyer
        settlement_phase: refund
        settlement_type: netbanking
        settlement_amount: "9040"
        settlement_timestamp: "2024-08-08T12:39:19.054Z"
  id: O1
  created_at: "2024-08-08T12:38:25.283Z"
  updated_at: "2024-08-08T12:51:57.593Z"
