message:
  tracking:
    id: F1
    location:
      gps: "12.9740,77.6134"
      time:
        timestamp: "2025-01-08T06:20:00.000Z"
      updated_at: "2025-01-08T06:30:00.000Z"
    url: "https://snp.com/ondc/tracking/F1"
    status: active
    tags:
      - code: order
        list:
          - code: id
            value: O1
      - code: config
        list:
          - code: attr
            value: tracking.location.gps
          - code: type
            value: live_poll
      - code: path
        list:
          - code: lat_lng
            value: "12.9740,77.6134"
          - code: sequence
            value: "1"
      - code: path
        list:
          - code: lat_lng
            value: "12.9740,77.6136"
          - code: sequence
            value: "2"
      - code: path
        list:
          - code: lat_lng
            value: "12.9740,77.6136"
          - code: sequence
            value: "3"
