message:
  intent:
    fulfillment:
      type: Delivery
    payment:
      '@ondc/org/buyer_app_finder_fee_type': percent
      '@ondc/org/buyer_app_finder_fee_amount': '3'
    tags:
    - code: bap_terms
      list:
        - code: static_terms
          value: ''
        - code: static_terms_new
          value: >-
            https://github.com/ONDC-Official/NP-Static-Terms/buyerNP_BNP/1.0/tc.pdf
        - code: effective_date
          value: '2025-02-01T00:00:00.000Z'
    - code: bap_features
      list:
        - code: '001'
          value: yes
