save-data:
  message_id: "$.context.message_id"
  updated_address: "$.message.order.fulfillments[*].end.location"
  updated_inst: "$.message.order.fulfillments[*].end.instructions"
  update_return_fulfillments: "$.message.order.fulfillments[*]"
  return_item_id: '$.message.order.fulfillments[*].tags[*].list[?(@.code=="item_id")].value'
  return_item_count: '$.message.order.fulfillments[*].tags[*].list[?(@.code=="item_quantity")].value'
  buyer_delivery_start_time: '$.message.order.fulfillments[*].tags[?(@.code=="update_state")].list[?(@.code=="start_time")].value'
  buyer_delivery_order_status: '$.message.order.fulfillments[*].tags[?(@.code=="update_state")].list[?(@.code=="state")].value'
