order:
  provider:
    id: P1
    locations:
      - id: L1
  items:
    - id: I1
      quantity:
        count: 1
      location_id: L1
      fulfillment_id: F1
  billing:
    address:
      building: my building name or house
      city: Bengaluru
      state: Karnataka
      country: IND
      area_code: "560027"
      locality: my street name
      name: my house or door or floor
    phone: "9898989898"
    name: ONDC Buyer
    email: nobody@nomail.com
    created_at: "2024-08-14T09:10:34.369Z"
    updated_at: "2024-08-14T09:10:34.369Z"
  fulfillments:
    - id: F1
      type: Delivery
      end:
        contact:
          email: nobody@nomail.com
          phone: "9898989898"
        location:
          gps: 12.966545,77.592074
          address:
            building: my building name or house
            city: Bengaluru
            state: Karnataka
            country: IND
            area_code: "560027"
            locality: my street name
            name: my house or door or floor
