codes:
  - code: 100
    default: FASHION/1.2.5/search/search/default.yaml
    action_id: search
    action: search
    message_id: true
  - code: 101
    default: FASHION/1.2.5/on_search/on_search/default.yaml
    action_id: on_search
    action: on_search
    message_id: false
  - code: 102
    default: FASHION/1.2.5/search/search_inc/default.yaml
    action_id: search_inc
    action: search
    message_id: true
  - code: 103
    default: FASHION/1.2.5/on_search/on_search_inc/default.yaml
    action_id: on_search_inc
    action: on_search
    message_id: true
  - code: 104
    default: FASHION/1.2.5/on_search/on_search_inc_disable/default.yaml
    action_id: on_search_inc_disable
    action: on_search
    message_id: true
  - code: 201
    default: FASHION/1.2.5/select/select/default.yaml
    action_id: select
    action: select
    message_id: true
  - code: 202
    default: FASHION/1.2.5/on_select/on_select/default.yaml
    action_id: on_select
    action: on_select
    message_id: false
  - code: 203
    default: FASHION/1.2.5/init/init/default.yaml
    action_id: init
    action: init
    message_id: true
  - code: 204
    default: FASHION/1.2.5/on_init/on_init/default.yaml
    action_id: on_init
    action: on_init
    message_id: false
  - code: 205
    default: FASHION/1.2.5/confirm/confirm/default.yaml
    action_id: confirm
    action: confirm
    message_id: true
  - code: 206
    default: FASHION/1.2.5/on_confirm/on_confirm/default.yaml
    action_id: on_confirm
    action: on_confirm
    message_id: false
  - code: 207
    default: FASHION/1.2.5/on_status/on_status_pending/default.yaml
    action_id: on_status_pending
    action: on_status
    message_id: true
  - code: 208
    default: FASHION/1.2.5/on_status/on_status_packed/default.yaml
    action_id: on_status_packed
    action: on_status
    message_id: true
  - code: 209
    default: FASHION/1.2.5/on_status/on_status_agent_assigned/default.yaml
    action_id: on_status_agent_assigned
    action: on_status
    message_id: true
  - code: 210
    default: FASHION/1.2.5/on_status/on_status_picked/default.yaml
    action_id: on_status_picked
    action: on_status
    message_id: true
  - code: 211
    default: FASHION/1.2.5/on_status/on_status_out_for_delivery/default.yaml
    action_id: on_status_out_for_delivery
    action: on_status
    message_id: true
  - code: 212
    default: FASHION/1.2.5/on_status/on_status_order_delivered/default.yaml
    action_id: on_status_order_delivered
    action: on_status
    message_id: true
  # - code: 116
  #   default: FASHION/1.2.5/track/track/default.yaml
  #   action_id: track
  #   action: track
  #   message_id: true
  # - code: 117
  #   default: FASHION/1.2.5/on_track/on_track/default.yaml
  #   action_id: on_track
  #   action: on_track
  #   message_id: false
  - code: 301
    default: FASHION/1.2.5/on_search/on_search_118/default.yaml
    action_id: on_search_118
    action: on_search
    message_id: false
  - code: 302
    default: FASHION/1.2.5/select/select_out_of_stock/default.yaml
    action_id: select_out_of_stock
    action: select
    message_id: true
  - code: 303
    default: FASHION/1.2.5/on_select/on_select_out_of_stock/default.yaml
    action_id: on_select_out_of_stock
    action: on_select
    message_id: false
  - code: 401
    default: FASHION/1.2.5/cancel/cancel/default.yaml
    action_id: cancel
    action: cancel
    message_id: true
  - code: 402
    default: FASHION/1.2.5/on_cancel/on_cancel/default.yaml
    action_id: on_cancel
    action: on_cancel
    message_id: false
  - code: 130
    default: FASHION/1.2.5/on_select/on_select_130/default.yaml
    action_id: on_select_130
    action: on_select
    message_id: false
  - code: 131
    default: FASHION/1.2.5/init/init_131/default.yaml
    action_id: init_131
    action: init
    message_id: true
  - code: 132
    default: FASHION/1.2.5/on_init/on_init_132/default.yaml
    action_id: on_init_132
    action: on_init
    message_id: false
  - code: 133
    default: FASHION/1.2.5/confirm/confirm_133/default.yaml
    action_id: confirm_133
    action: confirm
    message_id: true
  - code: 134
    default: FASHION/1.2.5/on_confirm/on_confirm_134/default.yaml
    action_id: on_confirm_134
    action: on_confirm
    message_id: false
  - code: 135
    default: FASHION/1.2.5/on_status/on_status_pending/default.yaml
    action_id: on_status_pending
    action: on_status
    message_id: false
  - code: 136
    default: FASHION/1.2.5/on_status/on_status_packed_136/default.yaml
    action_id: on_status_packed_136
    action: on_status
    message_id: false
  - code: 137
    default: FASHION/1.2.5/on_status/on_status_picked_137/default.yaml
    action_id: on_status_picked_137
    action: on_status
    message_id: false
  - code: 138
    default: FASHION/1.2.5/on_status/on_status_out_for_delivery_138/default.yaml
    action_id: on_status_out_for_delivery_138
    action: on_status
    message_id: false
  - code: 139
    default: FASHION/1.2.5/on_cancel/on_cancel_rto/default.yaml
    action_id: on_cancel_rto
    action: on_cancel
    message_id: false
  - code: 140
    default: FASHION/1.2.5/on_status/on_status_rto_delivereddisposed/default.yaml
    action_id: on_status_rto_delivereddisposed
    action: on_status
    message_id: false
  - code: 141
    default: FASHION/1.2.5/on_search/on_search_141/default.yaml
    action_id: on_search_141
    action: on_search
    message_id: false
  - code: 142
    default: FASHION/1.2.5/select/select_142/default.yaml
    action_id: select_142
    action: select
    message_id: true
  - code: 143
    default: FASHION/1.2.5/on_select/on_select_143/default.yaml
    action_id: on_select_143
    action: on_select
    message_id: false
  - code: 144
    default: FASHION/1.2.5/init/init_144/default.yaml
    action_id: init_144
    action: init
    message_id: true
  - code: 145
    default: FASHION/1.2.5/on_init/on_init_145/default.yaml
    action_id: on_init_145
    action: on_init
    message_id: false
  - code: 146
    default: FASHION/1.2.5/confirm/confirm_146/default.yaml
    action_id: confirm_146
    action: confirm
    message_id: true
  - code: 147
    default: FASHION/1.2.5/on_confirm/on_confirm_147/default.yaml
    action_id: on_confirm_147
    action: on_confirm
    message_id: false
  - code: 148
    default: FASHION/1.2.5/on_update/on_update_part_cancel/default.yaml
    action_id: on_update_part_cancel
    action: on_update
    message_id: false
  - code: 149
    default: FASHION/1.2.5/update/update_partial_cancel_settlement/default.yaml
    action_id: update_partial_cancel_settlement
    action: update
    message_id: true
  - code: 150
    default: FASHION/1.2.5/on_status/on_status_pending_150/default.yaml
    action_id: on_status_pending_150
    action: on_status
    message_id: false
  - code: 151
    default: FASHION/1.2.5/on_status/on_status_packed_151/default.yaml
    action_id: on_status_packed_151
    action: on_status
    message_id: false
  - code: 152
    default: FASHION/1.2.5/on_status/on_status_picked_152/default.yaml
    action_id: on_status_picked_152
    action: on_status
    message_id: false
  - code: 153
    default: FASHION/1.2.5/on_status/on_status_out_for_delivery_153/default.yaml
    action_id: on_status_out_for_delivery_153
    action: on_status
    message_id: false
  - code: 154
    default: FASHION/1.2.5/on_status/on_status_order_delivered_154/default.yaml
    action_id: on_status_order_delivered_154
    action: on_status
    message_id: false
  - code: 155
    default: FASHION/1.2.5/on_status/on_status_pending_155/default.yaml
    action_id: on_status_pending_155
    action: on_status
    message_id: false
  - code: 156
    default: FASHION/1.2.5/on_status/on_status_packed_156/default.yaml
    action_id: on_status_packed_156
    action: on_status
    message_id: false
  - code: 157
    default: FASHION/1.2.5/on_status/on_status_picked_157/default.yaml
    action_id: on_status_picked_157
    action: on_status
    message_id: false
  - code: 158
    default: FASHION/1.2.5/on_status/on_status_out_for_delivery_158/default.yaml
    action_id: on_status_out_for_delivery_158
    action: on_status
    message_id: false
  - code: 159
    default: FASHION/1.2.5/on_status/on_status_order_delivered_159/default.yaml
    action_id: on_status_order_delivered_159
    action: on_status
    message_id: false
  - code: 160
    default: FASHION/1.2.5/update/update_liquidated/default.yaml
    action_id: update_liquidated
    action: update
    message_id: true
  - code: 161
    default: FASHION/1.2.5/on_update/on_update_interim_liquidated/default.yaml
    action_id: on_update_interim_liquidated
    action: on_update
    message_id: false
  - code: 162
    default: FASHION/1.2.5/on_update/on_update_liquidated/default.yaml
    action_id: on_update_liquidated
    action: on_update
    message_id: false
  - code: 163
    default: FASHION/1.2.5/update/update_liquidated_settlement/default.yaml
    action_id: update_liquidated_settlement
    action: update
    message_id: true
  - code: 164
    default: FASHION/1.2.5/update/update_reverse_qc/default.yaml
    action_id: update_reverse_qc
    action: update
    message_id: true
  - code: 165
    default: FASHION/1.2.5/on_update/on_update_interim_reverseQc/default.yaml
    action_id: on_update_interim_reverseQc
    action: on_update
    message_id: false
  - code: 166
    default: FASHION/1.2.5/on_update/on_update_approved/default.yaml
    action_id: on_update_approved
    action: on_update
    message_id: false
  - code: 167
    default: FASHION/1.2.5/on_update/on_update_picked/default.yaml
    action_id: on_update_picked
    action: on_update
    message_id: false
  - code: 168
    default: FASHION/1.2.5/update/update_reverse_qc_settlement/default.yaml
    action_id: update_reverse_qc_settlement
    action: update
    message_id: true
  - code: 169
    default: FASHION/1.2.5/on_update/on_update_return_delivered/default.yaml
    action_id: on_update_return_delivered
    action: on_update
    message_id: false
  - code: 170
    default: FASHION/1.2.5/on_update/on_update_interim_reverse_qc/default.yaml
    action_id: on_update_interim_reverse_qc
    action: on_update
    message_id: false
  - code: 171
    default: FASHION/1.2.5/on_update/on_update_approval/default.yaml
    action_id: on_update_approval
    action: on_update
    message_id: false
  - code: 172
    default: FASHION/1.2.5/on_update/on_update_picked_172/default.yaml
    action_id: on_update_picked_172
    action: on_update
    message_id: false
  - code: 173
    default: FASHION/1.2.5/on_update/on_update_return_delivered_173/default.yaml
    action_id: on_update_return_delivered_173
    action: on_update
    message_id: false
  - code: 174
    default: FASHION/1.2.5/on_update/on_update_interim_liquidated_174/default.yaml
    action_id: on_update_interim_liquidated_174
    action: on_update
    message_id: false
  - code: 175
    default: FASHION/1.2.5/on_update/on_update_liquidated_175/default.yaml
    action_id: on_update_liquidated_175
    action: on_update
    message_id: false
