session_data:
  transaction_id: null
  message_id: null
  city: null
  inc_mode: null
  selected_items: []
  selected_fulfillments: []
  items: []
  provider: null
  billing: null
  fulfillments: []
  quote: null
  order_id: null
  payment: null
  order_state: null
  last_action: null
  mock_type: null
  domain: null
  on_search_items: []
  select_fulfillment: []
  confirm_created_at_timestamp: null
  on_confirm_updated_at_timestamp: null
  cancellation_reason_id: null
  on_status_updated_at: null
  stateCode: null
  cancellation: null
  np_type: null
