update_target: payment
order:
  id: O1
  fulfillments:
    - id: R1
      type: Return
  payment:
    "@ondc/org/settlement_details":
      - settlement_counterparty: buyer
        settlement_phase: refund
        settlement_type: netbanking
        settlement_amount: "1677.37"
        settlement_timestamp: "2024-08-08T12:53:07.618Z"
