update_target: payment
order:
  id: 2025-02-10-293522
  fulfillments:
    - id: 67a9ad8173aa689a957eaf54
      type: Return
  payment:
    '@ondc/org/settlement_details':
      - settlement_counterparty: buyer
        settlement_phase: refund
        settlement_type: netbanking
        settlement_amount: '500'
        settlement_timestamp: '2025-02-10T09:43:08.367Z'
