order:
  provider:
    id: oc_22
    locations:
      - id: location_15
  items:
    - id: oc_72
      quantity:
        count: 5
      location_id: location_15
      fulfillment_id: 05fddb5e0d6bfe1251975d039599c525
  billing:
    address:
      building: Building 230
      city: Bengaluru
      state: Karnataka
      country: IND
      area_code: '560002'
      locality: KR Market Pedestrian Subway
      name: Vishakh Chandran T
    phone: '09999999999'
    name: Vishakh Chandran T
    email: vishakhc@gmail.com
    created_at: '2025-02-10T07:27:02.436Z'
    updated_at: '2025-02-10T07:27:02.436Z'
  fulfillments:
    - id: 05fddb5e0d6bfe1251975d039599c525
      type: Delivery
      end:
        contact:
          email: vishakhc@gmail.com
          phone: '09999999999'
        location:
          gps: 12.963691,77.577137
          address:
            building: Building 230
            city: Bengaluru
            state: Karnataka
            country: IND
            area_code: '560002'
            locality: KR Market Pedestrian Subway
            name: Vishakh Chandran T
