save-data:
  bpp_id: "$.context.bpp_id"
  bpp_uri: "$.context.bpp_uri"
  # on_search_items: "$.message.catalog['bpp/providers'][*].items[*]"
  # np_type: $.message.catalog['bpp/descriptor'].tags[?(@.code=='bpp_terms')].list[?(@.code=='np_type')].value
  # on_search_offers: "$.message.catalog['bpp/providers'][*].offers[*]"
