catalog:
  bpp/providers:
    - id: P1
      items:
        - id: I1
          time:
            label: enable
            timestamp: "2024-08-12T05:30:48.998Z"
          parent_item_id: ""
          descriptor:
            name: Power Bank
            symbol: https://sellerNP.com/images/i1.png
            short_desc: A Power Bank is a portable charger designed to recharge your electronic devices when you're on the move. Ranging in size from slim, pocket-sized devices up to larger, higher-capacity Power Banks – they can be used to charge smartphones, tablets, earphones, smartwatches and other mobile devices.
            long_desc: A Power Bank is a portable charger designed to recharge your electronic devices when you're on the move. Ranging in size from slim, pocket-sized devices up to larger, higher-capacity Power Banks
            images:
              - https://sellerNP.com/images/i1.png
            code: 5:ESS45300
          quantity:
            unitized:
              measure:
                unit: unit
                value: "1"
            available:
              count: "99"
            maximum:
              count: "8"
          price:
            currency: INR
            value: "2460"
            maximum_value: "2460"
          category_id: Power Bank
          location_id: L1
          fulfillment_id: F1
          "@ondc/org/returnable": true
          "@ondc/org/cancellable": true
          "@ondc/org/available_on_cod": false
          "@ondc/org/time_to_ship": P2D
          "@ondc/org/seller_pickup_return": true
          "@ondc/org/return_window": P7D
          "@ondc/org/contact_details_consumer_care": Seller Business,test@gmail.com,9876543210
          "@ondc/org/statutory_reqs_packaged_commodities":
            manufacturer_or_packer_name: Seller Business
            manufacturer_or_packer_address: Seller Building Address, Jayanagar, Bengaluru, Karnataka, India - 560011
            common_or_generic_name_of_commodity: Power Bank
            month_year_of_manufacture_packing_import: NA
          tags:
            - code: origin
              list:
                - code: country
                  value: IND
            - code: attribute
              list:
                - code: brand
                  value: Shiv Electricals
                - code: weight
                  value: "103"
                - code: model
                  value: "2012"
                - code: breadth
                  value: "12.3"
                - code: length
                  value: "10.2"
                - code: height
                  value: "15.5"
        