message:
  order:
    provider:
      id: P1
      locations:
        - id: L1
    items:
      - id: "I1"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI1"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "item"
      - id: "C1"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI1"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG1"
      - id: "C7"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI1"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG2"
      - id: "C14"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI1"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG3"
      - id: "C16"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI1"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG3"
      - id: "I1"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI2"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "item"
      - id: "C2"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI2"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG1"
      - id: "C7"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI2"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG2"
      - id: "C14"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI2"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG3"
      - id: "C15"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI2"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG3"
    billing:
      name: ONDC buyer
      address:
        name: my house or door or floor #
        building: my building name or house #
        locality: my street name
        city: Bengaluru
        state: Karnataka
        country: IND
        area_code: "560037"
      tax_number: XXXXXXXXXXXXXXX
      email: nobody@nomail.com
      phone: "9886098860"
      created_at: "2025-01-08T09:00:00.000Z"
      updated_at: "2025-01-08T09:00:00.000Z"
    fulfillments:
      - id: F1
        type: Delivery
        tracking: false
        end:
          location:
            gps: 12.4535,77.9283
            address:
              name: my house or door or floor #
              building: my building name or house #
              locality: my street name
              city: Bengaluru
              state: Karnataka
              country: IND
              area_code: "560037"
          contact:
            phone: "9886098860"
    quote:
      price:
        currency: INR
        value: "1955.65"
      breakup:
        - "@ondc/org/item_id": I1
          "@ondc/org/item_quantity":
            count: 1
          title: Farm House Pizza
          "@ondc/org/title_type": item
          price:
            currency: INR
            value: "269.00"
          item:
            parent_item_id: DI1
            quantity:
              available:
                count: "99"
              maximum:
                count: "99"
            price:
              currency: INR
              value: "269.00"
            tags:
              - code: type
                list:
                  - code: type
                    value: item
        - "@ondc/org/item_id": C1
          "@ondc/org/item_quantity":
            count: 1
          title: New Hand Tossed
          "@ondc/org/title_type": item
          price:
            currency: INR
            value: "0.00"
          item:
            parent_item_id: DI1
            quantity:
              available:
                count: "99"
              maximum:
                count: "99"
            price:
              currency: INR
              value: "0.00"
            tags:
              - code: type
                list:
                  - code: type
                    value: customization
              - code: parent
                list:
                  - code: id
                    value: CG1
        - "@ondc/org/item_id": C7
          "@ondc/org/item_quantity":
            count: 1
          title: Large
          "@ondc/org/title_type": item
          price:
            currency: INR
            value: "450.00"
          item:
            parent_item_id: DI1
            quantity:
              available:
                count: "99"
              maximum:
                count: "99"
            price:
              currency: INR
              value: "450.00"
            tags:
              - code: type
                list:
                  - code: type
                    value: customization
              - code: parent
                list:
                  - code: id
                    value: CG2
      ttl: PT1H
    payment:
      "@ondc/org/buyer_app_finder_fee_type": percent
      "@ondc/org/buyer_app_finder_fee_amount": "3.54"
      "@ondc/org/settlement_details":
        - settlement_counterparty: seller-app
          settlement_phase: sale-amount
          settlement_type: upi
          beneficiary_name: xxxxx
          upi_address: gft@oksbi
          settlement_bank_account_no: XXXXXXXXXX
          settlement_ifsc_code: XXXXXXXXX
          bank_name: xxxx
          branch_name: xxxx
    cancellation_terms:
      - fulfillment_state:
          descriptor:
            code: Pending
            short_desc: "002"
        cancellation_fee:
          percentage: "0.00"
      - fulfillment_state:
          descriptor:
            code: Packed
            short_desc: "001,003"
        cancellation_fee:
          percentage: "100.00"
      - fulfillment_state:
          descriptor:
            code: Order-picked-up
            short_desc: "001,003"
        cancellation_fee:
          percentage: "100.00"
      - fulfillment_state:
          descriptor:
            code: At-pickup
            short_desc: "009"
        cancellation_fee:
          percentage: "100.00"
      - fulfillment_state:
          descriptor:
            code: At-delivery
            short_desc: "010,011,012,013,014,015"
        cancellation_fee:
          percentage: "100.00"
    tags:
      - code: bpp_terms
        list:
          - code: tax_number
            value: gst_number_of_sellerNP
          - code: provider_tax_number
            value: PAN_number_of_provider
