order:
  state: Cancelled
  items:
    - id: I1
      quantity:
        count: 0
      fulfillment_id: F1
    - id: I1
      quantity:
        count: 2
      fulfillment_id: F1-RTO
  provider:
    id: P1
    locations:
      - id: L1
  billing:
    address:
      building: my building name or house
      city: Bengaluru
      state: Karnataka
      country: IND
      area_code: "560027"
      locality: my street name
      name: my house or door or floor
    phone: "9898989898"
    name: ONDC buyer
    email: nobody@nomail.com
    created_at: "2024-08-08T10:01:24.650Z"
    updated_at: "2024-08-08T10:01:24.650Z"
  fulfillments:
    - id: F1
      "@ondc/org/provider_name": Seller Business
      "@ondc/org/TAT": P3D
      state:
        descriptor:
          code: Cancelled
      type: Delivery
      tracking: false
      start:
        location:
          id: L1
          descriptor:
            name: Seller Business
          gps: 12.925810,77.583624
          address:
            building: my building name or house
            country: IND
            locality: my street name
            city: Bengaluru
            area_code: "560011"
            state: Karnataka
            name: my house or door or floor
        contact:
          phone: "9594663710"
          email: nobody@nomail.com
        time:
          range:
            start: "2024-08-08T10:09:58.799Z"
            end: "2024-08-10T10:09:58.799Z"
          timestamp: "2024-08-08T10:10:49.202Z"
      end:
        person:
          name: John Doe
        contact:
          email: nobody@nomail.com
          phone: "9898989898"
        location:
          gps: 12.966545,77.592074
          address:
            building: my building name or house
            city: Bengaluru
            state: Karnataka
            country: IND
            area_code: "560027"
            locality: my street name
            name: my house or door or floor
        time:
          range:
            start: "2024-08-12T10:09:58.799Z"
            end: "2024-08-14T10:09:58.799Z"
      tags:
        - code: cancel_request
          list:
            - code: retry_count
              value: "1"
            - code: rto_id
              value: F1-RTO
            - code: reason_id
              value: "013"
            - code: initiated_by
              value: sellerNP.com
        - code: precancel_state
          list:
            - code: fulfillment_state
              value: Out-for-delivery
            - code: updated_at
              value: "2024-08-08T10:11:08.138Z"
    - id: F1-RTO
      type: RTO
      state:
        descriptor:
          code: RTO-Delivered
      start:
        contact:
          email: nobody@nomail.com
          phone: "9898989898"
        location:
          gps: 12.966545,77.592074
          address:
            building: my building name or house
            city: Bengaluru
            state: Karnataka
            country: IND
            area_code: "560027"
            locality: my street name
            name: my house or door or floor
        time:
          timestamp: "2024-08-08T10:11:24.749Z"
      end:
        location:
          id: L1
          descriptor:
            name: Seller Business
          gps: 12.925810,77.583624
          address:
            building: my building name or house
            country: IND
            locality: my street name
            city: Bengaluru
            area_code: "560011"
            state: Karnataka
            name: my house or door or floor
        contact:
          phone: "9594663710"
          email: nobody@nomail.com
        time:
          timestamp: "2025-01-28T11:38:31.210Z"
      tags:
        - code: quote_trail
          list:
            - code: type
              value: misc
            - code: id
              value: F1
            - code: currency
              value: INR
            - code: value
              value: "-3.00"
        - code: quote_trail
          list:
            - code: type
              value: item
            - code: id
              value: I1
            - code: currency
              value: INR
            - code: value
              value: "-2260.00"
  quote:
    price:
      currency: INR
      value: "493.75"
    breakup:
      - "@ondc/org/item_id": I1
        "@ondc/org/item_quantity":
          count: 1
        title: Butterfly Beautiful 13 Gold Necklace
        "@ondc/org/title_type": item
        price:
          currency: INR
          value: "0.00"
        item:
          price:
            currency: INR
            value: "2260.00"
      - "@ondc/org/item_id": F1
        title: Delivery charges
        "@ondc/org/title_type": delivery
        price:
          currency: INR
          value: "493.75"
      - "@ondc/org/item_id": F1
        title: Convenience Fee
        "@ondc/org/title_type": misc
        price:
          currency: INR
          value: "0.00"
    ttl: P1D
  payment:
    params:
      amount: "2756.75"
      currency: INR
      transaction_id: order_Okj0iihMKJod0V
    status: PAID
    type: ON-ORDER
    collected_by: BAP
    "@ondc/org/buyer_app_finder_fee_type": percent
    "@ondc/org/buyer_app_finder_fee_amount": "3.0"
    "@ondc/org/settlement_details":
      - settlement_counterparty: seller-app
        settlement_phase: sale-amount
        settlement_type: neft
        beneficiary_name: xxxx
        settlement_bank_account_no: xxxx
        settlement_ifsc_code: xxxx
        bank_name: xxxx
        branch_name: xxxx
      - settlement_counterparty: buyer
        settlement_phase: refund
        settlement_type: upi
        settlement_amount: "2263"
        settlement_timestamp: '2024-08-08T10:11:24.790Z'
  cancellation:
    cancelled_by: dev-automation.ondc.org
    reason:
      id: "013"
  documents:
    - url: https://dev-automation.ondc.org
      label: Invoice
  id: O1
  created_at: "2024-08-08T10:01:50.601Z"
  updated_at: "2024-08-08T10:11:24.790Z"
