order:
  provider:
    id: 5b3981a7-512d-4ac4-bd75-ea48eff89a53
    locations:
      - id: 668e238e1b106d310473ddb0
  fulfillments:
    - id: 3ac6a056-ceba-4c14-8e5d-ab5dd72d5239
      type: Delivery
      '@ondc/org/provider_name': Seller Business
      tracking: false
      '@ondc/org/category': Standard Delivery
      '@ondc/org/TAT': PT96H
      state:
        descriptor:
          code: Serviceable
  quote:
    price:
      value: '2853.75'
      currency: INR
    breakup:
      - '@ondc/org/item_id': 839cb128-34bd-444d-9ffc-05903e62b35a
        '@ondc/org/item_quantity':
          count: 1
        title: Butterfly Beutiful 12 Gold Necklace
        '@ondc/org/title_type': item
        price:
          currency: INR
          value: '2260.00'
        item:
          quantity:
            available:
              count: '99'
            maximum:
              count: '10'
          price:
            currency: INR
            value: '2260.00'
      - '@ondc/org/item_id': 3ac6a056-ceba-4c14-8e5d-ab5dd72d5239
        title: Delivery charges
        '@ondc/org/title_type': delivery
        price:
          currency: INR
          value: '493.75'
      - '@ondc/org/item_id': 3ac6a056-ceba-4c14-8e5d-ab5dd72d5239
        title: Convenience Fee
        '@ondc/org/title_type': misc
        price:
          currency: INR
          value: '100.00'
    ttl: P1D
  items:
    - id: 839cb128-34bd-444d-9ffc-05903e62b35a
      fulfillment_id: 3ac6a056-ceba-4c14-8e5d-ab5dd72d5239
