catalog:
  bpp/providers:
    - id: P1
      items:
        - id: I1
          time:
            label: enable
            timestamp: "2024-08-12T06:31:44.198Z"
          rating: "4"
          parent_item_id: V1
          descriptor:
            name: Butterfly Beautiful 12 Gold Necklace
            symbol: https://sellerNP.com/images/i1.png
            short_desc: 18KT Butterfly Beautiful 12 Gold Necklace Pendant with gold finishing
            long_desc:
              This is 18KT Butterfly Beautiful 12 Gold Necklace Pendant with gold
              finishing
            images:
              - https://sellerNP.com/images/i1.png
            code: 4:7113
          quantity:
            unitized:
              measure:
                unit: unit
                value: "1"
            available:
              count: "99"
            maximum:
              count: "8"
          price:
            currency: INR
            value: "2200"
            maximum_value: "2200"
          category_id: Necklaces
          location_id: L1
          fulfillment_id: F1
          "@ondc/org/returnable": true
          "@ondc/org/cancellable": true
          "@ondc/org/available_on_cod": false
          "@ondc/org/time_to_ship": P2D
          "@ondc/org/seller_pickup_return": true
          "@ondc/org/return_window": P7D
          "@ondc/org/contact_details_consumer_care": Seller Business,test@gmail.com,9876543210
          "@ondc/org/statutory_reqs_packaged_commodities":
            manufacturer_or_packer_name: Seller Business
            manufacturer_or_packer_address:
              Seller Building Address, Jayanagar, Bengaluru,
              Karnataka, India - 560011
            common_or_generic_name_of_commodity: Butterfly Beautiful 12 Gold Necklace
            month_year_of_manufacture_packing_import: NA
          tags:
            - code: origin
              list:
                - code: country
                  value: IND
            - code: attribute
              list:
                - code: colour_name
                  value: gold
                - code: gender
                  value: female
                - code: colour
                  value: "#C0C0C0"
                - code: base_metal
                  value: silver
                - code: plating
                  value: gold
                - code: size
                  value: "5"
                - code: brand
                  value: jewellery brand
