order:
provider:
  id: P1
  locations:
    - id: L1
state: Completed
items:
  - id: I1
    quantity:
      count: 0
    fulfillment_id: F1
  - id: I1
    fulfillment_id: C1
    quantity:
      count: 1
  - id: I1
    fulfillment_id: R1
    quantity:
      count: 1
billing:
  address:
    name: my house or door or floor
    building: my building name or house
    locality: my street name
    city: Bengaluru
    state: Karnataka
    country: IND
    area_code: '560027'
  phone: '9898989898'
  name: ONDC Buyer
  email: nobody@nomail.com
  created_at: '2024-08-14T09:10:34.369Z'
  updated_at: '2024-08-14T09:10:34.369Z'
fulfillments:
  - id: F1
    '@ondc/org/provider_name': Epic Store
    '@ondc/org/TAT': P3D
    state:
      descriptor:
        code: Out-for-delivery
    type: Delivery
    tracking: false
    start:
      location:
        id: L1
        descriptor:
          name: Epic Store
        gps: 28.679701,77.063873
        address:
          locality: Nangloi Extension
          city: New Delhi
          area_code: '110041'
          state: Delhi
      contact:
        email: rajesh@gmail.com
        phone: '8273946283'
      time:
        range:
          start: '2025-01-28T16:21:50.523Z'
          end: '2025-01-30T16:21:50.523Z'
        timestamp: '2025-01-28T16:22:03.129Z'
    end:
      person:
        name: your-name
      contact:
        phone: '9876543210'
      location:
        gps: 28.679077,77.069714
        address:
          name: my house or door or floor
          building: my building name or house
          locality: my street name
          city: Bengaluru
          state: Karnataka
          country: IND
          area_code: '560027'
      time:
        range:
          start: '2025-01-31T16:21:50.523Z'
          end: '2025-02-02T16:21:50.523Z'
        timestamp: '2025-01-28T16:22:19.740Z'
  - state:
      descriptor:
        code: Cancelled
    type: Cancel
    id: C1
    tags:
      - code: cancel_request
        list:
          - code: reason_id
            value: '002'
          - code: initiated_by
            value: your-id
      - code: quote_trail
        list:
          - code: type
            value: item
          - code: id
            value: I1
          - code: currency
            value: INR
          - code: value
            value: '-40829.48'
  - id: R1
    type: Return
    state:
      descriptor:
        code: Return_Delivered
    tags:
      - code: return_request
        list:
          - code: id
            value: R1
          - code: item_id
            value: I1
          - code: parent_item_id
            value: ''
          - code: item_quantity
            value: '1'
          - code: reason_id
            value: '001'
          - code: reason_desc
            value: detailed description for return
          - code: images
            value: ''
          - code: ttl_approval
            value: PT24H
          - code: ttl_reverseqc
            value: P3D
          - code: replace
            value: 'yes'
          - code: initiated_by
            value: yournp.com
      - code: replace_request
        list:
          - code: id
            value: FR1
      - code: quote_trail
        list:
          - code: type
            value: item
          - code: id
            value: I1
          - code: currency
            value: INR
          - code: value
            value: '-40829.48'
      - code: quote_trail
        list:
          - code: type
            value: delivery
          - code: id
            value: R1
          - code: currency
            value: INR
          - code: value
            value: '582.63'
    '@ondc/org/provider_name': Epic Store
    start:
      person:
        name: your-name
      contact:
        phone: '9876543210'
      location:
        gps: 28.679077,77.069714
        address:
          name: my house or door or floor
          building: my building name or house
          locality: my street name
          city: Bengaluru
          state: Karnataka
          country: IND
          area_code: '560027'
        descriptor:
          name: Epic Store
      time:
        timestamp: '2025-01-28T16:23:18.210Z'
    end:
      location:
        id: L1
        descriptor:
          name: Epic Store
        gps: 28.679701,77.063873
        address:
          locality: Nangloi Extension
          city: New Delhi
          area_code: '110041'
          state: Delhi
      contact:
        email: rajesh@gmail.com
        phone: '8273946283'
      time:
        timestamp: '2025-01-28T16:23:35.028Z'
  - id: FR1
    '@ondc/org/provider_name': Epic Store
    '@ondc/org/TAT': P3D
    state:
      descriptor:
        code: Pending
    type: Delivery
    tracking: false
    start:
      location:
        id: L1
        descriptor:
          name: Epic Store
        gps: 28.679701,77.063873
        address:
          locality: Nangloi Extension
          city: New Delhi
          area_code: '110041'
          state: Delhi
      contact:
        email: rajesh@gmail.com
        phone: '8273946283'
      time:
        range:
          start: '2025-01-28T17:21:50.523Z'
          end: '2025-01-30T17:21:50.523Z'
        timestamp: '2025-01-28T19:22:51.523Z'
    end:
      person:
        name: your-name
      contact:
        phone: '9876543210'
      location:
        gps: 28.679077,77.069714
        address:
          name: my house or door or floor
          building: my building name or house
          locality: my street name
          city: Bengaluru
          state: Karnataka
          country: IND
          area_code: '560027'
      time:
        range:
          start: '2024-08-11T12:39:03.396Z'
          end: '2024-08-13T12:39:03.396Z'
quote:
  price:
    currency: INR
    value: '582.63'
  breakup:
    - '@ondc/org/item_id': I1
      '@ondc/org/item_quantity':
        count: 0
      title: Golden Ring by saad
      '@ondc/org/title_type': item
      price:
        currency: INR
        value: '0.00'
      item:
        price:
          currency: INR
          value: '40829.48'
    - '@ondc/org/item_id': F1
      title: Delivery charges
      '@ondc/org/title_type': delivery
      price:
        currency: INR
        value: '0.00'
    - '@ondc/org/item_id': R1
      title: Delivery charges
      '@ondc/org/title_type': delivery
      price:
        currency: INR
        value: '582.63'
  ttl: P1D
payment:
  uri: https://razorpay.com/
  params:
    amount: '81658.96'
    currency: INR
    transaction_id: order_PovTljcF6RLpBs
  status: PAID
  type: ON-ORDER
  collected_by: BAP
  '@ondc/org/buyer_app_finder_fee_type': percent
  '@ondc/org/buyer_app_finder_fee_amount': '3.0'
  '@ondc/org/settlement_details':
    - settlement_counterparty: seller-app
      settlement_phase: sale-amount
      settlement_type: neft
      upi_address: gft@oksbi
      settlement_bank_account_no: xxxx
      settlement_ifsc_code: xxxx
      beneficiary_name: xxxx
      bank_name: xxxx
      branch_name: xxxx
    - settlement_counterparty: buyer
      settlement_phase: refund
      settlement_type: upi
      settlement_amount: '40829.48'
      settlement_timestamp: '2025-01-28T16:21:40.763Z'
id: 2025-01-28-470338
created_at: '2025-01-28T16:17:08.546Z'
updated_at: '2025-01-29T20:22:51.523Z'
documents:
  - url: https://invoice_url
    label: Invoice
