message:
  order:
    id: "O1"
    state: "Created"
    provider:
      id: P1
      locations:
        - id: L1
    items:
      - id: I1
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI1
        tags:
          - code: type
            list:
              - code: type
                value: item
      - id: C1
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI1
        tags:
          - code: type
            list:
              - code: type
                value: customization
          - code: parent
            list:
              - code: id
                value: CG1
      - id: C7
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI1
        tags:
          - code: type
            list:
              - code: type
                value: customization
          - code: parent
            list:
              - code: id
                value: CG2
      - id: C14
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI1
        tags:
          - code: type
            list:
              - code: type
                value: customization
          - code: parent
            list:
              - code: id
                value: CG3
      - id: C16
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI1
        tags:
          - code: type
            list:
              - code: type
                value: customization
          - code: parent
            list:
              - code: id
                value: CG3
      - id: I1
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI2
        tags:
          - code: type
            list:
              - code: type
                value: item
      - id: C2
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI2
        tags:
          - code: type
            list:
              - code: type
                value: customization
          - code: parent
            list:
              - code: id
                value: CG1
      - id: C7
        fulfillment_id: F1
        quantity:
          count: 1
        parent_item_id: DI2
        tags:
          - code: type
            list:
              - code: type
                value: customization
          - code: parent
            list:
              - code: id
                value: CG2
    billing:
      name: "ONDC buyer"
      address:
        name: "my house or door or floor #"
        building: "my building name or house #"
        locality: "my street name"
        city: "Bengaluru"
        state: "Karnataka"
        country: "IND"
        area_code: "560037"
      email: "nobody@nomail.com"
      phone: "9886098860"
      created_at: "2025-01-08T09:00:00.000Z"
      updated_at: "2025-01-08T09:00:00.000Z"
    fulfillments:
      - id: "F1"
        "@ondc/org/provider_name": "LSP or Provider Name"
        state:
          descriptor:
            code: "Pending"
        type: "Delivery"
        tracking: true
        "@ondc/org/TAT": "PT60M"
        start:
          location:
            id: "L1"
            descriptor:
              name: "ABC Store"
            gps: "12.9563,77.6368"
            address:
              locality: "Jayanagar"
              city: "Bengaluru"
              area_code: "560076"
              state: "KA"
          contact:
            phone: "9886098860"
            email: "nobody@nomail.com"
        end:
          location:
            gps: "12.4535,77.9283"
            address:
              name: "my house or door or floor #"
              building: "my building name or house #"
              locality: "my street name"
              city: "Bengaluru"
              state: "Karnataka"
              country: "IND"
              area_code: "560037"
          person:
            name: "name_of_person"
          contact:
            phone: "9886098860"
            email: "nobody@nomail.com"
    quote:
      price:
        currency: "INR"
        value: "1955.65"
      breakup:
        - "@ondc/org/item_id": "I1"
          "@ondc/org/item_quantity":
            count: 1
          title: "Farm House Pizza"
          "@ondc/org/title_type": "item"
          price:
            currency: "INR"
            value: "269.00"
          item:
            parent_item_id: "DI1"
            price:
              currency: "INR"
              value: "269.00"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "item"
        - "@ondc/org/item_id": "C1"
          "@ondc/org/item_quantity":
            count: 1
          title: "New Hand Tossed"
          "@ondc/org/title_type": "item"
          price:
            currency: "INR"
            value: "0.00"
          item:
            parent_item_id: "DI1"
            price:
              currency: "INR"
              value: "0.00"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG1"
        - "@ondc/org/item_id": "C7"
          "@ondc/org/item_quantity":
            count: 1
          title: "Large"
          "@ondc/org/title_type": "item"
          price:
            currency: "INR"
            value: "450.00"
          item:
            parent_item_id: "DI1"
            price:
              currency: "INR"
              value: "450.00"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG2"
        - "@ondc/org/item_id": "C14"
          "@ondc/org/item_quantity":
            count: 1
          title: "Grilled Mushrooms"
          "@ondc/org/title_type": "item"
          price:
            currency: "INR"
            value: "80.00"
          item:
            parent_item_id: "DI1"
            price:
              currency: "INR"
              value: "80.00"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG3"
        - "@ondc/org/item_id": "C16"
          "@ondc/org/item_quantity":
            count: 1
          title: "Pepper Barbeque Chicken"
          "@ondc/org/title_type": "item"
          price:
            currency: "INR"
            value: "95.00"
          item:
            parent_item_id: "DI1"
            price:
              currency: "INR"
              value: "95.00"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG3"
        - "@ondc/org/item_id": "I1"
          "@ondc/org/item_quantity":
            count: 1
          title: "Farm House Pizza"
          "@ondc/org/title_type": "item"
          price:
            currency: "INR"
            value: "269.00"
          item:
            parent_item_id: "DI2"
            price:
              currency: "INR"
              value: "269.00"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "item"
        - "@ondc/org/item_id": "C2"
          "@ondc/org/item_quantity":
            count: 1
          title: "100% Wheat Thin Crust"
          "@ondc/org/title_type": "item"
          price:
            currency: "INR"
            value: "0.00"
          item:
            parent_item_id: "DI2"
            price:
              currency: "INR"
              value: "0.00"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG1"
        - "@ondc/org/item_id": "C7"
          "@ondc/org/item_quantity":
            count: 1
          title: "Large"
          "@ondc/org/title_type": "item"
          price:
            currency: "INR"
            value: "450.00"
          item:
            parent_item_id: "DI2"
            price:
              currency: "INR"
              value: "450.00"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG2"
        - "@ondc/org/item_id": "C14"
          "@ondc/org/item_quantity":
            count: 1
          title: "Grilled Mushrooms"
          "@ondc/org/title_type": "item"
          price:
            currency: "INR"
            value: "80.00"
          item:
            parent_item_id: "DI2"
            price:
              currency: "INR"
              value: "80.00"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG3"
        - "@ondc/org/item_id": "C15"
          "@ondc/org/item_quantity":
            count: 1
          title: "Fresh Tomato"
          "@ondc/org/title_type": "item"
          price:
            currency: "INR"
            value: "80.00"
          item:
            parent_item_id: "DI2"
            price:
              currency: "INR"
              value: "80.00"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG3"
        - "@ondc/org/item_id": "I1"
          title: "Tax"
          "@ondc/org/title_type": "tax"
          price:
            currency: "INR"
            value: "13.45"
          item:
            parent_item_id: "DI1"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "item"
        - "@ondc/org/item_id": "C1"
          title: "Tax"
          "@ondc/org/title_type": "tax"
          price:
            currency: "INR"
            value: "0.00"
          item:
            parent_item_id: "DI1"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG1"
        - "@ondc/org/item_id": "C7"
          title: "Tax"
          "@ondc/org/title_type": "tax"
          price:
            currency: "INR"
            value: "22.50"
          item:
            parent_item_id: "DI1"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG2"
        - "@ondc/org/item_id": "C14"
          title: "Tax"
          "@ondc/org/title_type": "tax"
          price:
            currency: "INR"
            value: "4.00"
          item:
            parent_item_id: "DI1"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG3"
        - "@ondc/org/item_id": "C16"
          title: "Tax"
          "@ondc/org/title_type": "tax"
          price:
            currency: "INR"
            value: "4.75"
          item:
            parent_item_id: "DI1"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG1"
        - "@ondc/org/item_id": "I1"
          title: "Tax"
          "@ondc/org/title_type": "tax"
          price:
            currency: "INR"
            value: "13.45"
          item:
            parent_item_id: "DI2"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "item"
        - "@ondc/org/item_id": "C2"
          title: "Tax"
          "@ondc/org/title_type": "tax"
          price:
            currency: "INR"
            value: "22.50"
          item:
            parent_item_id: "DI2"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG1"
        - "@ondc/org/item_id": "C7"
          title: "Tax"
          "@ondc/org/title_type": "tax"
          price:
            currency: "INR"
            value: "22.50"
          item:
            parent_item_id: "DI2"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG2"
        - "@ondc/org/item_id": "C14"
          title: "Tax"
          "@ondc/org/title_type": "tax"
          price:
            currency: "INR"
            value: "4.00"
          item:
            parent_item_id: "DI2"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG3"
        - "@ondc/org/item_id": "C15"
          title: "Tax"
          "@ondc/org/title_type": "tax"
          price:
            currency: "INR"
            value: "4.00"
          item:
            parent_item_id: "DI2"
            tags:
              - code: "type"
                list:
                  - code: "type"
                    value: "customization"
              - code: "parent"
                list:
                  - code: "id"
                    value: "CG3"
        - "@ondc/org/item_id": "F1"
          title: "Delivery charges"
          "@ondc/org/title_type": "delivery"
          price:
            currency: "INR"
            value: "50.00"
        - "@ondc/org/item_id": "F1"
          title: "Tax"
          "@ondc/org/title_type": "tax"
          price:
            currency: "INR"
            value: "9.00"
          item:
            tags:
              - code: "quote"
                list:
                  - code: "type"
                    value: "fulfillment"
        - "@ondc/org/item_id": "F1"
          title: "Packing charges"
          "@ondc/org/title_type": "packing"
          price:
            currency: "INR"
            value: "25.00"
        - "@ondc/org/item_id": "F1"
          title: "Convenience Fee"
          "@ondc/org/title_type": "misc"
          price:
            currency: "INR"
            value: "10.00"
      ttl: "PT1H"
    payment:
      uri: "https://ondc.transaction.com/payment"
      tl_method: "http/get"
      params:
        currency: "INR"
        transaction_id: "3937"
        amount: "1955.65"
      status: "PAID"
      type: "ON-ORDER"
      collected_by: "BAP"
      "@ondc/org/buyer_app_finder_fee_type": "percent"
      "@ondc/org/buyer_app_finder_fee_amount": "3.54"
      "@ondc/org/settlement_basis": "delivery"
      "@ondc/org/settlement_window": "P1D"
      "@ondc/org/withholding_amount": "10.00"
      "@ondc/org/settlement_details":
        - settlement_counterparty: "seller-app"
          settlement_phase: "sale-amount"
          beneficiary_name: "xxxxx"
          settlement_type: "upi"
          upi_address: "gft@oksbi"
          settlement_bank_account_no: "XXXXXXXXXX"
          settlement_ifsc_code: "XXXXXXXXX"
          bank_name: "xxxx"
          branch_name: "xxxx"
    cancellation_terms:
      - fulfillment_state:
          descriptor:
            code: Pending
            short_desc: "002"
        cancellation_fee:
          percentage: "0.00"
      - fulfillment_state:
          descriptor:
            code: Packed
            short_desc: "001,003"
        cancellation_fee:
          percentage: "100.00"
      - fulfillment_state:
          descriptor:
            code: Order-picked-up
            short_desc: "001,003"
        cancellation_fee:
          percentage: "100.00"
      - fulfillment_state:
          descriptor:
            code: At-pickup
            short_desc: "009"
        cancellation_fee:
          percentage: "100.00"
      - fulfillment_state:
          descriptor:
            code: At-delivery
            short_desc: "010,011,012,013,014,015"
        cancellation_fee:
          percentage: "100.00"
    tags:
      - code: "bpp_terms"
        list:
          - code: "np_type"
            value: "ISN"
          - code: "tax_number"
            value: "gst_number_of_sellerNP"
          - code: "provider_tax_number"
            value: "PAN_number_of_provider"
          - code: "accept_bap_terms"
            value: "Y"
      - code: "bap_terms"
        list:
          - code: "static_terms"
            value: "https://github.com/ONDC-Official/protocol-network-extension/discussions/79"
          - code: "tax_number"
            value: "gst_number_of_buyerNP"
    created_at: "2025-01-08T09:30:00.000Z"
    updated_at: "2025-01-08T09:31:30.000Z"
