message:
  order:
    provider:
      id: "P1"
      locations:
        - id: "L1"
    items:
      - id: "I1"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI1"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "item"
      - id: "C1"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI1"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG1"
      - id: "C7"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI1"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG2"
      - id: "C14"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI1"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG3"
      - id: "C16"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI1"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG3"
      - id: "I1"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI2"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "item"
      - id: "C2"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI2"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG1"
      - id: "C7"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI2"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG2"
      - id: "C14"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI2"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG3"
      - id: "C15"
        fulfillment_id: "F1"
        quantity:
          count: 1
        parent_item_id: "DI2"
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG3"
    billing:
      name: "ONDC buyer"
      address:
        name: "my house or door or floor #"
        building: "my building name or house #"
        locality: "my street name"
        city: "Bengaluru"
        state: "Karnataka"
        country: "IND"
        area_code: "560037"
      email: "nobody@nomail.com"
      phone: "9886098860"
      created_at: "2025-01-08T09:00:00.000Z"
      updated_at: "2025-01-08T09:00:00.000Z"
    fulfillments:
      - id: "F1"
        type: "Delivery"
        end:
          location:
            gps: "12.4535,77.9283"
            address:
              name: "my house or door or floor #"
              building: "my building name or house #"
              locality: "my street name"
              city: "Bengaluru"
              state: "Karnataka"
              country: "IND"
              area_code: "560037"
          contact:
            phone: "9886098860"
