update_target: item
order:
  id: 2025-02-10-293522
  fulfillments:
    - type: Return
      tags:
        - code: return_request
          list:
            - code: id
              value: 67a9bfda73aa689a957ebafd
            - code: item_id
              value: oc_72
            - code: parent_item_id
              value: ''
            - code: item_quantity
              value: '1'
            - code: reason_id
              value: '002'
            - code: reason_desc
              value: detailed description for return
            - code: images
              value: >-
                https://reference-buyer-app-assets.s3-ap-south-1.amazonaws.com/public-assets/2025-02-10-293522/7da6288d-b324-48dd-ac16-331140cd0e4f.png
            - code: ttl_approval
              value: PT24H
            - code: ttl_reverseqc
              value: P3D
